terraform {
  backend "s3" {
    key                  = "terraform.tfstate"
    workspace_key_prefix = "asc-ftv-rank"
    encrypt              = true
    use_lockfile         = true
    # bucket + region intentionally omitted — supplied via
    # `terraform init -backend-config=../scripts/../infra/state-bucket-info.hcl`
    # (or wherever that file lands relative to this one), since the
    # bucket name is randomly generated by scripts/create_state_bucket.sh
    # and backend blocks can't reference variables/locals.
  }
}

provider "aws" {
  region = "us-east-1"
}
