#!/usr/bin/env bash
set -euo pipefail

# Initializes Terraform in infra/, using the backend config generated by
# create_state_bucket.sh (bucket + region for the S3 state backend).
#
# Can be run from anywhere (e.g. the project root) — it locates infra/
# relative to this script's own location.
# Assumes this script lives in scripts/ and infra/ is a sibling folder
# (e.g. repo-root/scripts/init_terraform.sh, repo-root/infra/).
#
# Usage:
#   ./init_terraform.sh [backend-config-file]
#
# Example:
#   ./init_terraform.sh
#   ./init_terraform.sh state-bucket-info.hcl

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INFRA_DIR="${SCRIPT_DIR}/../infra"
BACKEND_CONFIG="${1:-state-bucket-info.hcl}"

cd "${INFRA_DIR}"

if [ ! -f "${BACKEND_CONFIG}" ]; then
  echo "Error: backend config file '${BACKEND_CONFIG}' not found in ${INFRA_DIR}."
  echo "Run scripts/create_state_bucket.sh first, or pass the correct filename."
  exit 1
fi

echo "Initializing Terraform in ${INFRA_DIR} using backend config '${BACKEND_CONFIG}'..."
terraform init -backend-config="${BACKEND_CONFIG}"

echo
echo "Done. Current workspaces:"
terraform workspace list